FROM apache/airflow:2.10.0

USER root

RUN apt-get update && \
    apt-get install -y build-essential && \
    apt-get clean

USER airflow

COPY requirements /opt/airflow/requirements

RUN python -m pip install --upgrade pip && \
    pip install -r /opt/airflow/requirements/airflow.txt