FROM python:3.11-slim

WORKDIR /app

RUN python -m pip install --upgrade pip && \
    pip install --no-cache-dir mlflow

COPY . .

EXPOSE 5000

CMD ["mlflow", "ui", "--backend-store-uri", "sqlite:///mlflow.db", "--host", "0.0.0.0", "--port", "5000"]