FROM python:3.11-slim

WORKDIR /app

COPY requirements /app/requirements

RUN python -m pip install --upgrade pip && \
    pip install --no-cache-dir --default-timeout=300 -r requirements/api.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]