FROM jenkins/jenkins:lts

USER root

RUN apt-get update && \
    apt-get install -y \
    docker.io \
    git \
    python3 \
    python3-pip \
    python3-venv \
    sudo && \
    apt-get clean

RUN echo "jenkins ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

CMD ["/usr/bin/tini","--","/usr/local/bin/jenkins.sh"]